[project]
name = "sri-bhoovalaya-v4"
version = "1.0.0"
description = "Sri Bhoovalaya experimental stock research"
requires-python = ">=3.13,<3.15"

dependencies = [
    "flet",
    "requests"
]

[tool.flet]
product = "Sri Bhoovalaya V4"
org = "com.rajeshbhansali"
company = "Rajesh Bhansali"
copyright = "Copyright 2026 Rajesh Bhansali"

[tool.flet.android]
target_arch = ["arm64-v8a"]
